import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
    {/* children이라는 property는 page.js라는 파일의 값을 가져옴 */}
      <body>{children}</body>
    </html>
  )
}
